### ISSUE TITLE
Add SVG

### ISSUE THREAD

**Issue by ashahabov** [ShapeCrawler/ShapeCrawler#350]
Add the `IShapeCollection.AddNewPicture(int xCoordinate,  int yCoordinate, Stream svgContent)` method to able to add SVG picture:

```c#
using var pres = SCPresentation.Open("some.pptx");
var svgContent = new MemoryStream(File.ReadAllBytes("some.svg")); 
var shapeCollection = pres.Slides[0].Shapes;

shapeCollection.AddNewPicture(100, 100, svgStream);
```

**Comment by jcoliz** [comment]
@ashahabov This is something I need, so it may make sense to do it as part of ShapeCrawler if I have to figure it out anyway. Would you have any getting-started pointers on this?

**Comment by jcoliz** [comment]
FYI, I am working on this now. https://github.com/jcoliz/ShapeCrawler/tree/issue/350-add-svg. So far, so good. Reasonable passing tests. But I haven't actually confirmed by loading into PowerPoint yet.

**Comment by ashahabov** [comment]
> @ashahabov This is something I need, so it may make sense to do it as part of ShapeCrawler if I have to figure it out anyway. Would you have any getting-started pointers on this?

The SVG image format and 2D graphics in general are still new topics for me, so I am open to suggestions on this.

Currently, graphic manipulations are implemented using [SkiaSharp](https://github.com/mono/SkiaSharp). The idea was to use it for all graphics, if possible, without introducing an extra third-party library dependency.

One of the contributors planned to implement a feature to convert shape to SVG image. He suggested using the [svg-net/SVG](https://github.com/svg-net/SVG) library (I noticed you are also trying to use this library in your [PR](https://github.com/ShapeCrawler/ShapeCrawler/pull/675/files)). His feedback was that converting even a simple shape is challenging with SkiaSharp.

Unfortunately, the contributor disappeared after a few email messages🙂

**Comment by ashahabov** [comment]
> FYI, I am working on this now. https://github.com/jcoliz/ShapeCrawler/tree/issue/350-add-svg. So far, so good. Reasonable passing tests. But I haven't actually confirmed by loading into PowerPoint yet.

Thank you for your contributions!

**Comment by jcoliz** [comment]
@ashahabov Ok, I will have a look at SkiaSharp to see if this can be used instead. I have a large library of SVG graphics to import, so it will be a good test.

**Comment by jcoliz** [comment]
@ashahabov Update: Does not seem possible to do this with SkiaSharp. Based on my research this morning, I believe that dependency on SVG library is the only tractable solution to add SVG loading into ShapeCrawler.

* There was a https://www.nuget.org/packages/SkiaSharp.Svg library, however has not been released since 2018.
* SkiaSharp.Svg was folded into SkiaSharp.Extended.Svg
* SkiaSharp.Extended.Svg is now deprecated, see https://github.com/mono/SkiaSharp.Extended/issues/84.
* https://github.com/wieslawsoltes/Svg.Skia just uses same SKG library I'm using here, so now we'd have an indirect dependency.
